project:
  type: book

book:
  title: "Základy financí"
  author: "Tomáš Plíhal, Martina Sponerová"
  date: "2024-09-23"
  search: true
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  sidebar:
    logo: logo.png
  chapters:
    - index.qmd
    - week_01.qmd
    - week_02.qmd
    - week_03.qmd
    - week_04.qmd
    - week_05.qmd
    - week_06.qmd
    - week_07.qmd
    - week_08.qmd
    - week_09.qmd
    - week_10.qmd
    - week_11.qmd
    - week_12.qmd
    - week_13.qmd

format:
  html:
    theme: materia
    number-depth: 3
  pdf:
    documentclass: scrreprt



