---
title: "Untitled"
format: html
---

Week 01 (Tom)
      1 Introduction to Finance
      2 Corporate Structure and Governance
Week 02 (Tom)
      3 Economic Foundations: Money and Rates
Week 03 (Luďa)
      7 Time Value of Money I: Single Payment Value
      8 Time Value of Money II: Equal Multiple Payments
      9 Time Value of Money III: Unequal Multiple Payment Values
Week 04 (Luďa)
      10 Bonds and Bond Valuation
Week 05 (Tom)
      11 Stocks and Stock Valuation
Week 06 (Tom)
      12 Historical Performance of US Markets
Week 07 (Luďa)
      15 How to Think about Investing
Week 08 (Martina)
      5 Financial Statements
Week 09 (Martina)
      6 Measures of Financial Health
Week 10 (Martina)
      16 How Companies Think about Investing
Week 11 (Martina)
      17 How Firms Raise Capital
      19 The Importance of Trade Credit and Working Capital in Planning
Week 12 (Tom)
      - Buď opakování, nebo bankovnictví nebo deriváty. Záleží, jak budeme stíhat.
      20 Risk Management and the Financial Manager
