# Časová hodnota peněz

::: {.callout-note}
# Studijní materiály

- Dahlquist, J. R., &; Knight, R. (2022). Principles of finance. OpenStax, Rice
University. <https://openstax.org/details/books/principles-finance>
  - Chapter 7 - Time Value of Money I: Single Payment Value
  - Chapter 8 - Time Value of Money II: Equal Multiple Payments
  - Chapter 9 - Time Value of Money III: Unequal Multiple Payment Values
:::

**Výstupy z učení:**

1. Vysvětlit, proč má čas dopad na hodnotu peněz.
2. Chápat pojmy budoucí hodnota a současná hodnota.
3. Ovládat výpočet budoucí hodnoty pomocí jednoduchého i složeného úročení.
4. Dokázat spočítat současnou hodnotu peněžního toku.
5. Umět využívat vzroce pro výpočet anuity.

## Úvod do časové hodnoty peněz

- Koncept časové hodnoty peněz (TVM, time value of money) uvádí, že peníze dnes jsou
hodnotnější než peníze v budoucnosti.
- To je způsobeno třemi důvody: 
  1. potenciálem pro okamžité spoření/investování
  2. rizikem budoucích platebních selhání
  3. lidskou preferencí pro okamžitou spotřebu
- TVM motivuje ke spoření v současnosti za účelem dosažení budoucích zisků.
- TVM je klíčové pro informovaná finanční rozhodnutí s ohledem na faktory jako riziko,
úrokové sazby, inflace a výnos.
- Pomáhá ve finančním plánování, hodnocení firemních projektů, plánování důchodu a
osobních investičních rozhodnutí.
- Zatímco inflace snižuje budoucí hodnotu peněz, pozitivní efekt složeného úroku
prospívá spořitelům a investorům.
- Delší investiční období a vyšší úrokové sazby zvyšují hodnotu investovaných peněz.
- Základní finanční transakce je jednorázový peněžní tok buď přijatý nebo zaplacený.
- Všechny typy peněžních toků lze rozložit na sérii jednorázových částek.
- Pro ilustraci časové hodnoty peněz lze použít online kalkulačky, např. <https://www.calculator.net/interest-calculator.html>

## Základní terminologie

- **Současná hodnota** (PV, present value) $\rightarrow$ hodnota peněz dnes.
- **Budoucí hodnota** (FV, future value) $\rightarrow$ hodnota peněz v určitém čase v
budoucnosti.
- Příklad: Investujete 1000 na spořicí účtet v bance, která slibuje roční úrokovou sazbu 8%.
    - Současná hodnota = 1000
    - Budoucí hodnota za rok = vklad + úrok = 1000 + 80 = 1080

## Budoucí hodnota

### Jednoduché úročení

- **Jednoduché úročení** $\rightarrow$ úročí se pouze jistina (počáteční vklad).
- Př. Investujete 1000 na spořicí účet v bance, který slibuje úrok (r) 8% ročně. Jaká
bude hodnota investice za 2 roky?
  - FV za 2 roky = 1000 + 80 + 80 = 1160
- Obecný vzorec:
$$
FV = PV \times [1 + (r \times n)]
$$
- Př. Kolik naspoříte za 15 let při roční úrokové sazbě 8% a 10%?
  $$
  FV = 1000 \times (1 + [0.08 \times 15]) = 2200
  $$
  $$
  FV = 1000 \times (1 + [0.10 \times 15]) = 2500
  $$

### Složené úročení

- **Složené úročení** $\rightarrow$ úročí se jistina a všechny získané úroky.
- Př. Investujete 1000 na spořicí účet v bance, který slibuje úrok (r) 8% ročně. Po
prvním roce vložíte získané peníze zpět na účet. Kolik budete mít za 2 roky?
  $$
  FV = PV \times (1 + r) \times (1 + r) = 1000 \times 1.08 \times 1.08 = 1166
  $$
- Obecný vzorec:
  $$
  FV = PV \times (1 + r)^n
  $$
  - $n$ je počet úrokových období v letech
- Př. Kolik naspoříte za 15 let z původní částky 1000 při roční úrokové sazbě 8% a 10% s
použitím složeného úročení?
  $$
  FV = 1000 \times (1 + 0.08)^{15} = 3172.169 
  $$
  $$
  FV = 1000 \times (1 + 0.10)^{15} = 4177.248 
  $$

## Současná hodnota

- Diskontování umožňuje výpočet současné hodnoty pokud známe budoucí hodnotu a úrokovou
sazbu.
- Dlůžitý koncept pro rozhodování o investicích a jejich oceňování.
- Obecný vzorec: 
$$
PV = \frac{FV}{(1+r)^n}
$$

- Př. Máte možnost investice, která vám za jeden rok vyplatí 1000. Kolik budete ochotni
investovat dnes, pokud je běžná úroková sazba 8%? Jak se změní výsledek, pokud dostanete
1000 až za 7 let?
  $$
  PV = \frac{1000}{(1+ 0.08)^1} = 925.93
  $$
  $$
  PV = \frac{1000}{(1+ 0.08)^7} = 583.49
  $$

## Kratší časové intervaly než jeden rok

- Obecný vzorec: 
$$
FV = PV \times (1 + \frac{r}{m})^{n \times m}
$$ 
  - $m$ je počet úrokových období za rok
  - $n$ je počet let
- Př. Kolik naspoříte za 15 let z původní částky 1000 při roční úrokové sazbě 8% s
použitím složeného úročení pokud se bude úrok připisovat měsíčně/čtvrtletně?
  $$
  FV = 1000 \times (1 + \frac{0.08}{12})^{15 \times 12} = 3306.921
  $$
  $$
  FV = 1000 \times (1 + \frac{0.08}{4})^{15 \times 4} = 3281.031
  $$

## Anuita

- **Anuita** $\rightarrow$ série stejných peněžních toků v pravidelných intervalech.
- **Anuita běžná** (polhůtní) $\rightarrow$ peněžní toky nastávají na konci každého
obddobí.
- **Anuita splatná** (předlhůtní) $\rightarrow$ peněžní toky nastávají na začátku
každého období.

### Budoucí hodnota anuity

- Př. Na konci každého roku investujete 1000 po dobu tří let. Investice se zhodnocuje
úrokem 8%. Jaká bude budoucí hodnota investice? (běžná anuita)
$$
FV = 1000 \times 1.08^2 +1000 \times 1.08^1 +1000 \times 1.08^0 = 3246
$$

- Obecný vzorec pro běžnou anuitu: 
$$
\text{FVA} = \text{PMT} \times \frac{(1 + r)^n - 1}{r}
$$
  - FVA (future value of an ordinary annuity)
  - PMT (periodic equal payment)

- Obecný vzorec pro splatnou anuitu:
$$
\text{FVA} = \text{PMT} \times \frac{(1 + r)^n - 1}{r} \times (1 + r)
$$

### Perpetuita

- **Perpetuita** je typ anuity, který poskytuje nekonečnou sérii peněžních toků.
- Jinými slovy, peněžní toky pokračují na dobu neurčitou.
- Často se používá pro oceňování preferovaných akcií.
- Obecný vzorec pro současnou hodnotu (PV) perpetuity je:
$$
PV = \frac{C}{r}
$$
- kde:
    - $C$ je konstantní peněžní tok přijatý za každé období,
    - $r$ je diskontní sazba nebo úroková sazba.

- Vzorec předpokládá, že první platba je provedena na konci prvního období, peněžní toky
jsou konstatní a pokračují na dobu neurčitou.
- Př. Předpokládejte, že zvažujete investování do
perpetuity, která slibuje platbu 500 na konci každého roku na dobu neurčitou a úroková
sazba je 5%. Současná hodnota této perpetuity by byla:
$$
PV = \frac{500}{0.05} = 10000
$$
- Takže byste měli být ochotni zaplatit až 10 000 za tuto perpetuitu.

### Jak dlouho trvá naspořit milion?

- Výpočet s využitím běžné anuity.
- Jednorázová investice 10 000:

| Úroková sazba (%) | Čas v letech |
|:-----------------:|:------------:|
|  5                | 94,4         |
| 10                | 48,3         |
| 15                | 33,0         |
| 20                | 25,3         |

- Pravidelná investice 10 000 ročně:

| Úroková sazba (%) | Čas v letech |
|:-----------------:|:------------:|
|  5                | 36,7         |
| 10                | 25,2         |
| 15                | 19,8         |
| 20                | 16,7         |

### Současná hodnota anuity

- Používá se např. k oceňování investic.
- Př. Mate možnost investice, která vám za 1 rok vyplatí 1000 a poté ještě další 2 roky
budete dostávat stejnou částku. Kolik jste ochotni za danou investici zaplatit pokud je
běžná úroková sazba 8%?
$$
PV = 1000 \times \frac{1}{1,08^1} + 1000 \times \frac{1}{1,08^2} + 1000 \times
\frac{1}{1,08^3} = 2577
$$

- Obecný vzorec pro běžnou anuitu:
$$
\text{PVA} = \text{PMT} \times \frac{1 - \frac{1}{(1 + r)^n}}{r}
$$
  - PVA (present value of an ordinary annuity)
  - PMT (periodic equal payment)

- Obecný vzorec pro splatnou anuitu: 
$$
\text{PVA} = \text{PMT} \times \frac{1 - \frac{1}{(1 + r)^n}}{r} \times (1+r)
$$
