# Time Value of Money

::: {.callout-note}
# Study Materials

- Dahlquist, J. R., &; Knight, R. (2022). Principles of finance. OpenStax, Rice
University. <https://openstax.org/details/books/principles-finance>
  - Chapter 7 - Time Value of Money I: Single Payment Value
  - Chapter 8 - Time Value of Money II: Equal Multiple Payments
  - Chapter 9 - Time Value of Money III: Unequal Multiple Payment Values
:::


**Learning Outcomes:**

By the end of this section, you will be able to:
• Explain why time has an impact on the value of money.
• Explain the concepts of future value and present value.
• Explain why lump sum cash flow is the basis for all other cash flows.

By the end of this section, you will be able to:
• Define
future value and provide examples.
• Explain how future dollar amounts are calculated using a single-period scenario.
• Describe the impact of compounding.


## Now versus Later Concepts

- The Time Value of Money (TVM) concept states that a dollar today is worth more
than a dollar in the future.
- This is due to three reasons: potential for immediate saving/investment, risk
of future payment defaults, and human preference for immediate consumption.
- TVM concept incentivizes present saving for future gains.
- TVM is critical for making informed financial decisions considering factors
like risk, interest rates, inflation, and return.
- It helps in goal-oriented financial planning, corporate project evaluation,
retirement planning, and personal investment decisions.
- While inflation reduces future money value, the positive effect of compound
interest benefits savers and investors.
- Longer investment periods and higher interest rates enhance the growth of
invested money.
- The basic financial transaction, a lump sum, is a one-time cash flow either
received or paid. 
- All types of cash flow can be broken down into a series of lump sums,
emphasizing the need to understand the mathematics associated with lump sums.

## Basic Terminology

- ***Present Value*** (PV) $\rightarrow$ the value of money today.
- ***Future Value*** (FV) $\rightarrow$ the value of money at a given time in
the future.
- Example: You invest 1000 in a savings account in a bank, which promises an
annual interest rate (r) of 8%.
  - Present value = 1000
  - Future value in a year = deposit + interest = 1000 + 80 = 1080

## Future Value

### Simple Interest

- ***Simple interest*** $\rightarrow$ only the principal amount (initial
deposit) earns interest.
- Example: You invest 1000 in a savings account in a bank, which promises an
annual interest rate (r) of 8%. What will be the value of the investment in 2
years?
  - FV in 2 years = 1000 + 80 + 80 = 1160
- General formula:
$$
FV = PV \times [1 + (r \times T)] 
$$ 
- Example: How much will you save in 15 years with an annual interest rate of 8% and 10%?
$$
FV = 1000 \times (1 + [0.08 \times 15]) = 2200
$$
$$
FV = 1000 \times (1 + [0.10 \times 15]) = 2500
$$

### Compound Interest

- ***Compound interest*** $\rightarrow$ both the principal amount and all
accrued interest earn interest.
- Example: You invest 1000 in a savings account in a bank, which promises an
annual interest rate (r) of 8%. After the first year, you deposit the earned
money back into the account. How much will you have in 2 years?
$$
FV = PV \times (1 + r) \times (1 + r) = 1000 \times 1.08 \times 1.08 = 1166
$$
- General formula: $$ FV = PV \times (1 + r)^n $$
  - $n$ is the number of interest periods in years
  - $r$ is the interest rate per period
- Example: How much will you save in 15 years from an initial amount of 1000 at
an annual interest rate of 8% and 10% using compound interest?
$$
FV = 1000 \times (1 + 0.08)^{15} = 3172.169 
$$
$$
FV = 1000 \times (1 + 0.10)^{15} = 4177.248 
$$

## Present Value (Discounting)

- Allows the calculation of the present value if we know the future value and
the interest rate.
- Important for decision-making about investments and their valuation.
- General formula:
$$
PV = \frac{FV}{(1+r)^n}
$$
- Example: You have the opportunity to invest, which will pay you 1000 in one
year. How much are you willing to invest today if the common interest rate is
8%? How will the result change if you receive 1000 only after 7 years?
$$
PV = \frac{1000}{(1+ 0.8)^1} = 925.93
$$
$$
PV = \frac{1000}{(1+ 0.8)^7} = 583.49
$$

## Shorter time intervals than one year

- General formula: $$ FV = PV \times (1 + \frac{r}{m})^{n \times m} $$ 
  - $m$ is the number of interest periods per year
  - $n$ is the number of years
- Example: How much will you save in 15 years from the original amount of 1000
at an annual interest rate of 8% using compound interest if interest is accrued
monthly/quarterly?
$$
FV = 1000 \times (1 + \frac{0.08}{12})^{15 \times 12} = 3306.921
$$
$$
FV = 1000 \times (1 + \frac{0.08}{4})^{15 \times 4} = 3281.031
$$

## Annuity

- ***Annuity*** $\rightarrow$ a series of equal cash flows at regular intervals
- ***Ordinary annuity*** $\rightarrow$ cash flows occur at the end of each
period
- ***Annuity due*** $\rightarrow$ cash flows occur at the beginning of each
period

### Future Value of an Annuity

- Example: At the end of each year, you invest 1000 for three years. The
investment appreciates with an interest of 8%. What will be the future value of
the investment? (ordinary annuity)
$$
FV = 1000 \times 1.08^2 +1000 \times 1.08^1 +1000 \times 1.08^0 = 3246
$$

- General formula for ordinary annuity:
$$
\text{FVA} = \text{PMT} \times \frac{(1 + r)^n - 1}{r}
$$
  - FVA (future value of an ordinary annuity)
  - PMT (periodic equal payment)

- General formula for annuity due:
$$
\text{FVA} = \text{PMT} \times \frac{(1 + r)^n - 1}{r} \times (1 + r)
$$

### Perpetuity

- A **perpetuity** is a type of annuity that provides an infinite series of cash
flows. In other words, the cash flows continue indefinitely.
- It is often used for valuing preferred stocks.
- The general formula for the present value (PV) of a perpetuity is given as:
$$
PV = \frac{C}{r}
$$
- where:
    - $C$ is the constant cash flow received per period,
    - $r$ is the discount rate or interest rate.

- The formula assumes that the first payment is made one period from the
present, and since the cash flows are constant and continue indefinitely, the
future value cannot be computed.
- Let's consider a numerical example: Suppose you are considering investing in a
perpetuity that promises to pay $500 at the end of each year, indefinitely, and
the interest rate is 5%. The present value of this perpetuity would be:
$$
PV = \frac{500}{0.05} = \$10,000
$$
- So, you should be willing to pay up to $10,000 for this perpetuity.

### How long does it take to save a million?

- Using an ordinary annuity.
- Single investment of 10,000.

| Interest Rate (%) | Time (years) |
|:-----------------:|:------------:|
|  5                | 94.4         |
| 10                | 48.3         |
| 15                | 33.0         |
| 20                | 25.3         |

- Regular investments of 10,000 per year.

| Interest Rate (%) | Time (years) |
|:-----------------:|:------------:|
|  5                | 36.7         |
| 10                | 25.2         |
| 15                | 19.8         |
| 20                | 16.7         |

### Present Value of an Annuity

- Used, for example, to value investments.
- Example: You have the opportunity to invest, which will pay you 1000 in one
year, and then you will receive the same amount for the next 2 years. How much
are you willing to pay for this investment if the common interest rate is 8%?
$$
PV = 1000 \times \frac{1}{1.08^1} + 1000 \times \frac{1}{1.08^2} + 1000 \times \frac{1}{1.08^3} = 2577
$$

- General formula for ordinary annuity:
$$
\text{PVA} = \text{PMT} \times \frac{1 - \frac{1}{(1 + r)^n}}{r}
$$
  - PVA (present value of an ordinary annuity)
  - PMT (periodic equal payment)

- General formula for annuity due:
$$
\text{PVA} = \text{PMT} \times \frac{1 - \frac{1}{(1 + r)^n}}{r} \times (1+r)
$$

## Online Calculators
- https://www.calculator.net/interest-calculator.html